export const homeData = [
  {
    id: 1,
    name: "Gold Dust",
    rating: 4.7,
    time: "1hr : 40mins",
    desc: "Along the Mexico border,two friends search for a ghost ship rumored to be buried in the desert sand.In the same area, drug lords employ children; the duo must decide between going after the ship or saving a young girl held captive.",
    starring: "Darin Brooks, Chriss Romano, Burns Burns",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "07-April-2020",
  },
  {
    id: 2,
    name: "skull island",
    rating: 4.6,
    time: "1hr : 58mins",
    desc: "Shipwrecked in the South Pacific, a group of explorers encounter a menagerie of fearsome creatures — including the giant ape who rules the island: Kong.",
    starring: "Tom Hiddleston, Samuel L.Jackson, Brie Larson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "27-February-2017",
  },
  {
    id: 3,
    name: "The Sea Beast",
    rating: 4.8,
    time: "1hr : 59mins",
    desc: "When a young girl stows away on the ship of a legendary sea monster hunter, they launch an epic journey into uncharted waters — and make history to boot. ",
    starring: "Karl Urban, Zaris-Angel Hator, Jared Harris",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "15-June-2022",
  },
  {
    id: 4,
    name: "Heart of Stone",
    rating: 4.9,
    time: "2hr : 2mins",
    desc: "Heart of Stone sees Rachel Stone, a spy who works for a secret agency, trying to prevent the agency’s most powerful and dangerous AI technology from falling into the wrong hands",
    starring: "Gal Gadat, Jamie Dornan, Alia Bhatt",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "11-August-2023",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Despicable Me 4",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "57 Seconds",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Radical",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Fighter",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Ballerina",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.jpg",
    name: "How to Blow Up a Pipeline",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "Barbie",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u8.jpg",
    name: "Past Lives",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u9.jpg",
    name: "Mission: Impossible",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u10.jpg",
    name: "Sick of Myself",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "Oppenheimer",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "The story of an American scientist and his role in the development of an atomic bomb ",
    starring: "Cillian Murphy, Emily Blunt ,Matt Damon",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide1.jpg",
    date: "08-May-2023",
  },
  {
    id: 2,
    name: "Barbie",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "Barbie suffers a crisis that leads her to question her world and her existence ",
    starring: "Margot Robbie, Ryan Gosling, IssaRae",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "19-JULY-2023",
  },
  {
    id: 3,
    name: "Strays",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "An abandoned dog teams up with other strays to get revenge on his former owner ",
    starring: "Will Ferrel, Jamie Foxx, Isla Fisher",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2023",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "Zombie Island",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadow",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]
